name: Snyk Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Configuramos la versión de Python que tú quieras
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14' 

      # Usamos la CLI de Snyk directamente sobre el código
      - name: Snyk Test
        uses: snyk/actions/python@master # Nota: Sin el "-3.14"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      # 2. Construir y Escanear la imagen Docker
      - name: Build Docker image
        run: docker build -t swiss-re-assignment:latest .

      - name: Snyk Container monitor
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: swiss-re-assignment:latest
          args: --file=Dockerfile
