name: Snyk Security Scan

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Escanear el código Python (dependencias)
      - name: Snyk Python test
        uses: snyk/actions/python-3.9@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      # 2. Construir y Escanear la imagen Docker
      - name: Build Docker image
        run: docker build -t swiss-re-assignment:latest .

      - name: Snyk Container monitor
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: swiss-re-assignment:latest
          args: --file=Dockerfile